### PR TITLE
Added footer and background

### PR DESCRIPTION
**Pull request by Dishi2003Jain**
added footer and change background

### CODE REVIEW

**Comment by Lakshit-Chiranjiv** [comment]
Its all good , but I think the previous background was a bit better than this one, Could you put the same background again? or if any other color you wish which kinda suits ironman...

**Comment by Dishi2003Jain** [comment]
@Lakshit-Chiranjiv I have modified it

**Comment by Dishi2003Jain** [comment]
@Lakshit-Chiranjiv pls check it out

**Comment by Lakshit-Chiranjiv** [comment]
Ok done...All good
Thanks for contributing

**Pull request merged**
