### PR TITLE
animation added to the title bar

### PR DESCRIPTION
**Pull request by Hitanshuverma**
these are some screenshots these sentenced type themselves in the animation 

Screenshot 2021-10-17 212016

Screenshot 2021-10-17 212031

Screenshot 2021-10-17 212107

Screenshot 2021-10-17 212046

### CODE REVIEW

**Comment by Hitanshuverma** [comment]
@Lakshit-Chiranjiv  this is how the final title looks like..
#3 
3D IronMan hover effect - Google Chrome 2021-10-17 22-59-09

**Comment by Hitanshuverma** [comment]
@Lakshit-Chiranjiv  can you pls review the animation and merge it ASAP

**Comment by Lakshit-Chiranjiv** [comment]
I am reviewing the changes , by the time please first fetch the upstream commits to the forked repo and make this a practise always. Your forked repo is 4 commits behind the actual repo. There will be a fetch upstream option on forked repo page. Click it and then click fetch and merge.

**Comment by Hitanshuverma** [comment]
done

**Comment by Lakshit-Chiranjiv** [comment]
### 2 things need to be done:-

1) I have formatted 3 files = jquery.min.js , jquery.min.map , typed.min.js
    Your files are not formatted correctly so it would be a tough time for the new contributors to understand the code
    So , copy and paste & replace the files in your commit with the content provided the files given below as txt files.

[jqueryminjs.txt](https://github.com/Lakshit-Chiranjiv/Ironman-Snap/files/7367317/jqueryminjs.txt)
[jqueryminmap.txt](https://github.com/Lakshit-Chiranjiv/Ironman-Snap/files/7367318/jqueryminmap.txt)
[typedminjs.txt](https://github.com/Lakshit-Chiranjiv/Ironman-Snap/files/7367319/typedminjs.txt)


2) Also add a few comment lines in the 4 files you have added explaining the purpose of the respective files. Again for the same reason for the new contributors.

**Comment by Hitanshuverma** [comment]
jquery.min.js , jquery.min.map , typed.min.js are jquery pluggins hence they are not meant to be read by anyone they just provide functionality.
main.js is the one I created

**Comment by Lakshit-Chiranjiv** [comment]
Ok then just replace the content with the correctly formatted content ....that would be enough

**Comment by Hitanshuverma** [comment]
I have replaced the files with the formatted ones

**Pull request merged**
