### PR TITLE
fix:Helmet that are linked to each suit specifications

### PR DESCRIPTION
**Pull request by hvb24**
#7 
image
### @Lakshit-Chiranjiv I have linked helmet to their suits so whenever you click a helmet you will be directed to its own specific suit information website.

### CODE REVIEW

**Comment by hvb24** [comment]
@Lakshit-Chiranjiv Please check it out.

**Comment by hvb24** [comment]
@Lakshit-Chiranjiv can you check the code and merge it soon?

**Comment by Lakshit-Chiranjiv** [comment]
Reviewing the code, by the time I have added the label

**Comment by Lakshit-Chiranjiv** [comment]
Are you sure that it will look good and aligned even on a 14 inch screen?? I guess you are using a bigger screen size so its suitable for that only . You also need to consider the laptop users with small screen size.
See this
ironsite

**Comment by Lakshit-Chiranjiv** [comment]
make sure the arrangement of helmets doesn't look bad on smaller screen sizes as well and it doesn't disrupts the size of the main image. You can change the placement and also decrease the size for the helmets and also make sure they are the same size , mark42 looks a bit big.

**Comment by hvb24** [comment]
@Lakshit-Chiranjiv ok I will work on it asap.

**Comment by hvb24** [comment]
@Lakshit-Chiranjiv 
image
how about now?
I changed mark42 helmet so its looking good with others.
image

**Comment by Lakshit-Chiranjiv** [comment]
Yes these are quite good, just make sure that even in smaller screen sizes , the main image is not disrupted.

**Comment by hvb24** [comment]
@Lakshit-Chiranjiv 
image
is it ok now?

**Comment by Lakshit-Chiranjiv** [comment]
just give a little more margin top and bottom

**Comment by hvb24** [comment]
image

Bottom-
image
Now?? @Lakshit-Chiranjiv

**Comment by Lakshit-Chiranjiv** [comment]
Yup, thats better

**Comment by Lakshit-Chiranjiv** [comment]
Commit those changes in this PR and also fetch and merge other changes done in the repo ,then after review it will get merged

**Comment by hvb24** [comment]
@Lakshit-Chiranjiv check it out as I have resolved the conflicts.

**Pull request merged**
